channel_priority: strict
channels:
  - conda-forge
dependencies:
  - imagemagick=7.0.10_0
  - r-base=3.6
  - r-dt
  - r-rocr
  - r-broom
  - r-car
  - r-corrplot
  - r-corrr
  - r-dplyr
  - r-gapminder
  - r-ggbeeswarm
  - r-ggplot2
  - r-ggrepel
  - r-ggsignif
  - r-ggstance
  - r-ggthemes
  - r-haven
  - r-magrittr
  - r-margins
  - r-msm
  - r-patchwork
  - r-plyr
  - r-psych
  - r-purrr
  - r-rcompanion
  - r-readr
  - r-readxl
  - r-rmarkdown
  - r-sf
  - r-sjplot
  - r-stargazer
  - r-tidyverse
  - r-arm
  - r-biocmanager
  - r-checkmate
  - r-coda
  - r-corpcor
  - r-fdrtool
  - r-formula
  - r-ggplotify
  - r-glasso
  - r-gridgraphics
  - r-hmisc
  - r-htmltable
  - r-igraph
  - r-jpeg
  - r-latticeextra
  - r-lavaan
  - r-magick=2.6.0
  - r-pander
  - r-pbapply
  - r-pbivnorm
  - r-png
  - r-pryr
  - r-rapportools
  - r-reshape
  - r-rpart
  - r-rvcheck
